### ISSUE TITLE
VIDEOJS: ERROR: TypeError: Cannot read properties of undefined (reading 'parts' | 'videoTimingInfo' | 'audioTimingInfo' | 'start' | 'end')

### ISSUE THREAD

**Issue by Aigor79** [videojs/http-streaming#1275]

**Comment by gesinger** [comment]
We haven't been able to reproduce the issue yet ourselves. Does anyone have a reproducible test case that demonstrates the issue, or a segment that specifically triggers the errors? Thank you.

**Comment by Aigor79** [comment]
I think the problem occurs when network performance degrades. I often have experience of this problem while playing within a large private network (spread across the nation, in my case): video fragments sometimes get deteriorated and this causes error

**Comment by IndexLibrary** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading 'parts')
at SegmentLoader.chooseNextRequest_ (video.es.js:41474:1)
    at SegmentLoader.fillBuffer_ (video.es.js:41419:1)
    at SegmentLoader.monitorBufferTick_ (video.es.js:41391:1)

When the live stop and restart, the error occurs.

**Comment by duongthaison98** [comment]
![image](https://github.com/videojs/http-streaming/assets/94069709/17b638c5-5ea4-44e7-a226-50a5720a01b3)
I have the same problems. It stopped streaming when this happened
