### ISSUE TITLE
HLS Video Freezes and Buffers on Android Chrome

### ISSUE THREAD

**Issue by harinath01** [videojs/http-streaming#1481]
## Description
- While playing HLS videos on Video.js in Android Chrome (specific version), I've encountered a recurring problem where the video frequently freezes, while the audio continues playing in the background. After a short freeze period, the player buffers and resumes playback. and this issue seems specific to Android Chrome.

## Sources
- https://d384padtbeqfgy.cloudfront.net/transcoded/5E7JHcgdsF4/720p/video.m3u8

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Go to [https://videojs-http-streaming.netlify.app/](https://videojs-http-streaming.netlify.app/?debug=true&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=true&url=https%3A%2F%2Fd2zihajmogu5jn.cloudfront.net%2Fbipbop-advanced%2Fbipbop_16x9_variant.m3u8&type=application%2Fx-mpegurl&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&dts-offset=false&override-native=true&preload=auto&mirror-source=true&forced-subtitles=false)
2. Paste the above URL as a source URL and load the player.
3. You can see the video freezing around the 32nd and 44th seconds for example.

### Expected
Please describe what you expected to happen that did not happen in the description.
- Video should play without freezing or buffering frequently.

### Error output
If there are any errors in the console, from the player, or anywhere else please include them here:
Getting this error in the console on Android Chrome, although it doesn't appear to be directly related. Including it for reference.

```
video.core.js:210 VIDEOJS: ERROR: TypeError: Class constructor MenuButton cannot be invoked without 'new'
    at new SourceMenuButton (videojs-http-source-selector.js:87:27)
    at ControlBar.addChild (video.core.js:4213:21)
    at Player.<anonymous> (videojs-http-source-selector.js:233:49)
    at data.dispatcher (video.core.js:2206:33)
    at trigger (video.core.js:2337:27)
    at Player.trigger (video.core.js:3204:14)
    at Player.<computed> [as handleTechLoadedmetadata_] (video.core.js:27354:19)
    at Player.<anonymous> (video.core.js:23417:81)
    at data.dispatcher (video.core.js:2206:33)
```

## Additional Information
Please include any additional information necessary here. Including the following:
- The same source works fine with the hls.js player https://hlsjs.video-dev.org/demo/

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
- videojs-http-streaming 3.11.0

### videojs version
what version of videojs does this occur with?
- video.js 8.11.0

### Browsers
what browsers are affected? please include browser and version for each
* Android chrome - 121.0.6167.101

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Android 11; RMX2001 Build/RPIA.200720.011

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* None

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* None

**Comment by wonkwangzong** [comment]
Have you found a solution to this problem? I'm asking because the same phenomenon occurred to me.

**Comment by harinath01** [comment]
No, @wonkwangzong I haven't found it yet. Still working on it

**Comment by mister-ben** [comment]
FWIW, I don't observe any pausing on that video with a very slightly different Chrome version (121.0.6167.143) on a Pixel 7 with Android 14.
The Class constructor error is a red herring, do to with a plugin and not impacting playback, and won't display now.

**Comment by harinath01** [comment]
@mister-ben Thank you for checking it, but this problem specifically occurs on Oppo and Realme mobile devices.

**Comment by yonga00** [comment]
hello. I am experiencing freezing when seeking on the HLS VOD service.

Could this be a similar phenomenon?

This only happens in Android Chrome and does not occur in Samsung browsers.

What do other people think?

**Comment by leonatajeff** [comment]
Any luck? @harinath01 I'm experiencing the same on Android Chrome 113.0.5672.136. I have a Pixel 2 XL emulator but this seems to be reproducible on physical Android devices too.
