### ISSUE TITLE
Cannot read properties of undefined (reading 'duration')

### ISSUE THREAD

**Issue by victordidenko** [videojs/http-streaming#1559]
We have many errors in the Sentry, which looks like this
```
{
message: Cannot read properties of undefined (reading 'duration'),
name: TypeError,
stack: 
TypeError: Cannot read properties of undefined (reading 'duration')
    at Tf (.../player.js:188:3879)
    at CD.getExpiredTime (.../player.js:218:3581)
    at WD.stuckAtPlaylistEnd_ (.../player.js:218:45386)
    at kh.<anonymous> (.../player.js:218:37265)
    at i.dispatcher.i.dispatcher (.../player.js:23:40858)
    at Qh (.../player.js:23:41677)
    at kh.trigger (.../player.js:23:43393)
    at kh.haveMetadata (.../player.js:188:17321)
    at .../player.js:188:15997
    at Z_ (.../player.js:188:25260)
}
```
Unfortunately I cannot say conditions for this issue, I've never seen it in dev environment, but it is very frequent (in fact, this is the most repeating error in our Sentry), but from minified code I figured that this is `sumDurations` function:
https://github.com/videojs/http-streaming/blob/fef62d94fa1d39446f77699d6814e7b947d46dd1/src/playlist.js#L320
<img width="630" alt="Image" src="https://github.com/user-attachments/assets/dfbeb217-d0d5-4331-95b2-440052cefe7f" />

Maybe it is possible to add some kind of a guard here, at least?
Like
```js
durations += durationList[i]?.duration ?? 0;
```

**Comment by adrums86** [comment]
Do you have an example manifest we could create a reduced test case with? I think we need a little more information to determine what is causing the `durationList` to be undefined in this case

**Comment by victordidenko** [comment]
I will try to find stream, but this may be happen in some circumstances, which are not fully depend on a stream... Unfortunately, Sentry logs from production doesn't show full image, and as I say, I've never seen this error in development environment.

But what could be wrong in adding nullish guard?

**Comment by adrums86** [comment]
Simply trying to understand why this is happening in your environment and not more common elsewhere. Nothing wrong with a nullish guard, feel free to submit a PR. However a quick look at the code suggests there might be a bigger problem with the media if the `durationList` is undefined. Meaning a nullish guard might only push the problem further down stream. The `durationList` is generated from the `reduce` output from the media playlist. See: [playlist.js](https://github.com/videojs/http-streaming/blob/fef62d94fa1d39446f77699d6814e7b947d46dd1/src/playlist.js#L56).

**Comment by victordidenko** [comment]
The issue is that we provide software for an external company, and do not own streams. I'll ask our QA engineers, if they have access to the client's production server.

Meanwhile, in the Sentry I saw different stacktrace with the similar error:
```
{
message: Cannot read properties of undefined (reading 'duration'),
name: TypeError,
stack: 
TypeError: Cannot read properties of undefined (reading 'duration')
    at AE.calculateBaseTime_ (.../player.js:218:343)
    at AE.update (.../player.js:215:7438)
    at n0.playlist (.../player.js:203:56263)
    at WD.handleUpdatedMediaPlaylist (.../player.js:218:38102)
    at Ch.<anonymous> (.../player.js:218:36246)
    at i.dispatcher.i.dispatcher (.../player.js:23:40858)
    at Jh (.../player.js:23:41677)
    at Ch.trigger (.../player.js:23:43393)
    at Ch.haveMetadata (.../player.js:188:17546)
    at .../player.js:188:15997
}
```

This looks like this place:
https://github.com/videojs/http-streaming/blob/fef62d94fa1d39446f77699d6814e7b947d46dd1/src/util/media-sequence-sync.js#L253

**Comment by lukgeisler** [comment]
We’ve encountered the same issue during playback on our side, but unfortunately can’t share the stream publicly. However, the issue occurs under the following scenario:
- Start playback on a lower bitrate rendition
- Switch to a higher bitrate rendition
- During sync, we hit a stale playlist scenario where `mediaSequenceDiff` is significantly larger than `segments.length`
- As a result, the backward extrapolation loop in calculateBaseTime_ iterates beyond the bounds of segments[], causing a failure when accessing segment.duration (undefined)

[calculateBaseTime_(mediaSequence, segments, fallback)](https://github.com/videojs/http-streaming/blob/fef62d94fa1d39446f77699d6814e7b947d46dd1/src/util/media-sequence-sync.js#L231)

<img width="775" height="308" alt="Image" src="https://github.com/user-attachments/assets/2866148b-011d-4c71-8c90-1b7cfd35f57f" />

Would it be feasible to add a guard here, at least as a fallback ?
Like

```
 if (mediaSequenceDiff > segments.length) {
    return fallback;
  }
```
