### ISSUE TITLE
Failed to read the 'buffered' property from 'SourceBuffer' for some specific HLS media

### ISSUE THREAD

**Issue by dizzam** [videojs/http-streaming#508]
## Description
Cannot play HLS media showing in the attachment. Note that most videos work fine only for a small range of videos, which is generated by FFMpeg above 4.0 (FFMpeg 3.4.2 and below do not reproduce the issue), using the following command
```
ffmpeg <input> -c:v h264 -c:a aac -preset slower -crf 28 -s hd480 -hls_playlist_type vod -f hls out.m3u8
```
## Sources
[issue.zip](https://github.com/videojs/http-streaming/files/3171486/issue.zip) (Maybe you need a web server to avoid CORS issue)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Open `index.html`

### Expected
Just play the video for me

### Error output
```
video.js:142 VIDEOJS: ERROR: DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
    at Object.get$$1 (video-js/plugin/videojs-http-streaming.js:11806:31)
    at buffered (video-js/plugin/videojs-http-streaming.js:11724:20)
    at VirtualSourceBuffer.get$$1 (video-js/plugin/videojs-http-streaming.js:11945:17)
    at SourceUpdater.buffered (video-js/plugin/videojs-http-streaming.js:16806:34)
    at VirtualSourceBuffer.onUpdateendCallback_ (video-js/plugin/videojs-http-streaming.js:16734:62)
    at VirtualSourceBuffer.data.dispatcher (video-js/video.js:1818:33)
    at trigger (video-js/video.js:1954:27)
    at VirtualSourceBuffer.EventTarget.trigger (video-js/video.js:2436:5)
    at SourceBuffer.<anonymous> (video-js/plugin/videojs-http-streaming.js:12109:30)
```
## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
videojs-http-streaming 1.10.1 (57a38e994836b3a4a14c5885b0e7dd444c718238)

### videojs version
what version of videojs does this occur with?
video.js 7.5.4 (videojs/video-js@1a52b6971e4b7c46faab6ee62a9064186939d5f6)

### Browsers
Chrome 73.0.3683.86

### Platforms
Windows

### Other Plugins
No

### Other JavaScript
No

**Comment by grkblood13** [comment]
experiencing the same problem
