### ISSUE TITLE
VIDEOJS: ERROR: DOMException: Failed to execute 'remove' on 'SourceBuffer': This SourceBuffer is still processing an 'appendBuffer' or 'remove' operation.

### ISSUE THREAD

**Issue by asadmalik3** [videojs/http-streaming#864]
## Description
Sometimes when playing 4k HLS video, there is an error logged in console. Error is given in error output section.

## Sources
I don't have a link for this as it is not reproduced every time.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Playback 4k HLS video in chrome browser
2. Open debugging tools
3. Some times this error is logged in console tab

### Expected
No error should be logged

### Error output
`VIDEOJS: ERROR: DOMException: Failed to execute 'remove' on 'SourceBuffer': This SourceBuffer is still processing an 'appendBuffer' or 'remove' operation.
    at Object.i.<computed>.n.<computed> [as remove] (http://shah.beta.vidizmo.com/static/js/video-js/video.js?v=6.0.14245:21:75376)
    at Zl.value (http://dummy.com/static/js/video-js/video.js:21:77100)
    at yc.<anonymous> (http://dummy.com/static/js/video-js/video.js:21:98104)
    at yc.value (http://dummy.com/static/js/video-js/video.js:21:98748)
    at Zl.onUpdateendCallback_ (http://dummy.com/static/js/video-js/video.js:21:97114)
    at Zl.o.dispatcher.o.dispatcher (http://dummy.com/static/js/video-js/video.js:12:9892)
    at le (http://dummy.com/static/js/video-js/video.js:12:10670)
    at Zl.fe.dispatchEvent.fe.trigger (http://dummy.com/static/js/video-js/video.js:12:12262)
    at SourceBuffer.<anonymous> (http://dummy.com/static/js/video-js/video.js:21:75941)
    at e.invokeTask (http://dummy.com/static/compiled/theme-one/6.0.14245/vendor.js:1:194959)`

## Additional Information
Details about video:
**Video duration**: 11 seconds
**Video quality**: 4k
**Protocol**: HLS
**Chunk duration**: 11 seconds
**Each Chunk size**: 32 mb
**Total chunks in playlist**: 1
**Encoding provider**: WOWZA

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 1.10.6

### videojs version
what version of videojs does this occur with?
video.js 7.6.5

### Browsers
what browsers are affected? please include browser and version for each
* Chrome 83.0.4103.97 (Official Build) (64-bit)

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* Windows 10

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* Angular

**Comment by mithlesh-kumar** [comment]
@asadmalik3 Have you be able to resolve this issue?
