### ISSUE TITLE
Npm install 404

### ISSUE THREAD

**Issue by BeastHon** [videojs/http-streaming#925]
When i npm install my project, it return an 404 error

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/hon/.nvm/versions/node/v10.19.0/bin/node',
1 verbose cli   '/home/hon/.nvm/versions/node/v10.19.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@videojs/http-streaming' ]
2 info using npm@6.14.5
3 info using node@v10.19.0
4 verbose npm-session 10769a197d7ebdde
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@videojs%2fhttp-streaming 137ms
8 http fetch GET 404 https://registry.npmjs.org/@videojs%2fhttp-streaming 37ms
9 silly fetchPackageMetaData error for @videojs/http-streaming@^1.13.2 404 Not Found - GET https://registry.npmjs.org/@videojs%2fhttp-streaming - Not found
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 2545ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@videojs%2fhttp-streaming - Not found
12 verbose stack     at res.buffer.catch.then.body (/home/hon/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
12 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
13 verbose statusCode 404
14 verbose pkgid @videojs/http-streaming@^1.13.2
15 verbose cwd /storage/workspace/munroads/web-doorway
16 verbose Linux 4.15.0-112-generic
17 verbose argv "/home/hon/.nvm/versions/node/v10.19.0/bin/node" "/home/hon/.nvm/versions/node/v10.19.0/bin/npm" "install" "@videojs/http-streaming"
18 verbose node v10.19.0
19 verbose npm  v6.14.5
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/@videojs%2fhttp-streaming - Not found
22 error 404
23 error 404 '@videojs/http-streaming@^1.13.2' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]
```

**Comment by 951759534** [comment]
+1

**Comment by LeipeLeon** [comment]
NPM registry is having issues: https://status.npmjs.org/

**Comment by gkatsev** [comment]
Thanks @LeipeLeon. This must be it.
